---
x-authentik-service: &authentik-service
  image: ghcr.io/runleveldev/homelabcloud/authentik-server:2025.6.4-1
  build:
    context: ./images/authentik-server
  depends_on: &authentik-service_depends-on
    docker-socket-proxy:
      condition: service_healthy
    postgresql:
      condition: service_healthy
    redis:
      condition: service_healthy
  volumes:
    - authentik_media:/media
    - authentik_certs:/certs
    - authentik_templates:/templates
  restart: unless-stopped
  environment:
    AUTHENTIK_BOOTSTRAP_EMAIL: ${AUTHENTIK_BOOTSTRAP_EMAIL}
    AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    AUTHENTIK_REDIS__HOST: redis
    AUTHENTIK_POSTGRESQL__HOST: postgresql
    AUTHENTIK_POSTGRESQL__USER: authentik
    AUTHENTIK_POSTGRESQL__NAME: authentik
    AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    AUTHENTIK_LOG_LEVEL: debug
    BASE_DOMAIN: ${BASE_DOMAIN}
    GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
    GITHUB_SECRET: ${GITHUB_SECRET}

name: homelabcloud
services:
  authentik-init:
    <<: *authentik-service
    entrypoint: sh
    command: -c 'ak apply_blueprint /blueprints/custom/*'
    restart: on-failure:3
    depends_on:
      <<: *authentik-service_depends-on
      authentik-server:
        condition: service_healthy
  authentik-server:
    <<: *authentik-service
    command: server
    healthcheck:
      test: [ "CMD", "ak", "healthcheck" ]
    labels:
      traefik.enable: true
      traefik.http.routers.authentik.rule: Host(`auth.${BASE_DOMAIN}`)
      traefik.http.routers.authentik.entrypoints: websecure
    expose:
      - '9000'
      - '9443'
  authentik-worker:
    <<: *authentik-service
    command: worker
    healthcheck:
      test: [ "CMD", "ak", "healthcheck" ]
  docker-socket-proxy:
    image: docker.io/tecnativa/docker-socket-proxy:0.3.0
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
    environment:
      ALLOW_RESTARTS: 1
      CONTAINERS: 1
      IMAGES: 1
      INFO: 1
      POST: 1
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:2375/_ping" ]
    security_opt:
      - label=disable
  postgresql:
    image: docker.io/library/postgres:16-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
  redis:
    image: docker.io/library/redis:alpine
    volumes:
      - redis:/data
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
  traefik:
    image: docker.io/library/traefik:v3.5
    depends_on:
      docker-socket-proxy:
        condition: service_healthy
    volumes:
      - certs:/certs
    ports:
      - '9000:80'
      - '9443:443'
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certresolver=letsencrypt
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=tcp://docker-socket-proxy:2375
      - --certificatesresolvers.letsencrypt.acme.email=${AUTHENTIK_BOOTSTRAP_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/certs/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --api.dashboard=true
      - --api.insecure=false
      - --log.level=DEBUG
      - --accesslog=true
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.dashboard.rule: Host(`dashboard.${BASE_DOMAIN}`)
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.middlewares: authentik@docker

      traefik.http.middlewares.authentik.forwardauth.address: http://ak-outpost-proxy-outpost:9000/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
volumes:
  certs:
    driver: local
  postgresql:
    driver: local
  redis:
    driver: local
  authentik_media:
    driver: local
  authentik_templates:
    driver: local
  authentik_certs:
    driver: local
